language: python
sudo: false

# keep pypy first!
python:
- pypy
- '3.6'
- '3.5'
- '2.7'
- '3.4'
- '3.3'
- pypy3.5-5.8.0
- '2.6'

env:
  global:
  - CIBW_TEST_REQUIRES='pytest'
  - CIBW_TEST_COMMAND='pytest -v {project}/test'
  matrix:
  - ADMESH=0.98.3
  - ADMESH=0.98.2

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/admesh/python-admesh/admesh-$ADMESH
  - .eggs

install:
- if [ ! -f admesh-$ADMESH/.libs/admesh ]; then
      wget https://github.com/admesh/admesh/releases/download/v$ADMESH/admesh-$ADMESH.tar.gz;
      tar -zxf admesh-$ADMESH.tar.gz;
      cd admesh-$ADMESH;
      "./configure";
      make;
      mkdir src/admesh;
      cp src/stl.h src/admesh/stl.h;
      cd ..;
  fi
- pip install tox-travis Cython
script: LD_LIBRARY_PATH=$PWD/admesh-$ADMESH/.libs LDFLAGS=-L$PWD/admesh-$ADMESH/.libs CFLAGS=-I$PWD/admesh-$ADMESH/src tox

matrix:
  include:
  - sudo: required
    services:
    - docker
    env: CIBW_SKIP='*i686'
         CIBW_BEFORE_BUILD='rpm -q admesh-devel || yum install -y --nogpgcheck /project/travis/*.x86_64.rpm; {pip} install Cython'
    install:
    - pip install cibuildwheel==0.5.1
    script:
    - cibuildwheel --output-dir dist
  - sudo: required
    services:
    - docker
    env: CIBW_SKIP='*x86_64'
         CIBW_BEFORE_BUILD='rpm -q admesh-devel || yum install -y --nogpgcheck /project/travis/*.i386.rpm; {pip} install Cython'
    install:
    - pip install cibuildwheel==0.5.1
    script:
    - cibuildwheel --output-dir dist
  - os: osx
    language: generic
    env: CIBW_BEFORE_BUILD='{pip} install pytest-runner Cython'
    before_install:
    - brew install admesh
    install:
    - pip install cibuildwheel==0.5.1 Cython
    script:
    - cibuildwheel --output-dir dist
  allow_failures:
    - os: osx
  fast_finish: true

deploy:
  provider: pypi
  skip_cleanup: true
  user: hroncok
  password:
    secure: KAJOtf4HDXzL1LQsqGVPoHPniLcGcSwHvtp6gyiLUFwKmhIoqd7+ONSCVfDBCuIysOcsyXHGt1piMrMgyvuykupnFu43MDatWYk9KqaBs6/gyhoI/Ha7tavAiTMlaToEyNQGh7K6FZoVbVpEELtnuytRkWPqGfNTonEpWnmWMKw=
  on:
    tags: true
    repo: admesh/python-admesh
    python: pypy

# pypy up here will match the "normal" build as well as cibuildwheel
