language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
- pypy3
env:
- ADMESH=0.98.1
# Use the new container-based infrastructure
sudo: false
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/build/admesh/python-admesh/admesh-$ADMESH
before_install:
- if [ ! -f admesh-$ADMESH/.libs/admesh ]; then
      wget https://github.com/admesh/admesh/releases/download/v$ADMESH/admesh-$ADMESH.tar.gz;
      tar -zxf admesh-$ADMESH.tar.gz;
      cd admesh-$ADMESH;
      "./configure";
      make;
      mkdir src/admesh;
      cp src/stl.h src/admesh/stl.h;
      cd ..;
  fi
install:
- pip install -r requirements.txt
- LDFLAGS=-Ladmesh-$ADMESH/.libs CFLAGS=-Iadmesh-$ADMESH/src python setup.py install
script: LD_LIBRARY_PATH=admesh-$ADMESH/.libs py.test -v
deploy:
  provider: pypi
  user: hroncok
  password:
    secure: KAJOtf4HDXzL1LQsqGVPoHPniLcGcSwHvtp6gyiLUFwKmhIoqd7+ONSCVfDBCuIysOcsyXHGt1piMrMgyvuykupnFu43MDatWYk9KqaBs6/gyhoI/Ha7tavAiTMlaToEyNQGh7K6FZoVbVpEELtnuytRkWPqGfNTonEpWnmWMKw=
  on:
    tags: true
    repo: admesh/python-admesh
