language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - wget https://github.com/admesh/admesh/releases/download/v0.98.0/admesh-0.98.0.tar.gz
  - tar -zxf admesh-0.98.0.tar.gz
  - cd admesh-0.98.0
  - ./configure
  - make
  - sudo make install
  - cd ..
install:
  - pip install Cython
  - python setup.py install
script: LD_LIBRARY_PATH=/usr/local/lib py.test -v
