language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - wget https://github.com/admesh/admesh/releases/download/v0.98.1/admesh-0.98.1.tar.gz
  - tar -zxf admesh-0.98.1.tar.gz
  - cd admesh-0.98.1
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
install:
  - pip install -r requirements.txt
  - python setup.py install
script: py.test -v
